#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
#
echo 'prepare-commit-msg'
echo $0, $1, $2, $3
NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "$NAME"': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION"  ] 
then
    echo "" >> "$1"
    echo $DESCRIPTION >> "$1"
fi 
